// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v3.18.0
// source: msg.proto

package msgcode

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HeadFlag int32

const (
	HeadFlag_Notify  HeadFlag = 0 // 正常的消息
	HeadFlag_RPCReq  HeadFlag = 1 // rpc请求 需要填充HeadRPC.rpcID，全局唯一
	HeadFlag_RPCResp HeadFlag = 2 // rpc返回 需要填充rpc请求时的HeadRPC.rpcID
	HeadFlag_User    HeadFlag = 3 // 转发用户的消息 需要填充HeadUser
)

// Enum value maps for HeadFlag.
var (
	HeadFlag_name = map[int32]string{
		0: "Notify",
		1: "RPCReq",
		2: "RPCResp",
		3: "User",
	}
	HeadFlag_value = map[string]int32{
		"Notify":  0,
		"RPCReq":  1,
		"RPCResp": 2,
		"User":    3,
	}
)

func (x HeadFlag) Enum() *HeadFlag {
	p := new(HeadFlag)
	*p = x
	return p
}

func (x HeadFlag) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HeadFlag) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_proto_enumTypes[0].Descriptor()
}

func (HeadFlag) Type() protoreflect.EnumType {
	return &file_msg_proto_enumTypes[0]
}

func (x HeadFlag) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HeadFlag.Descriptor instead.
func (HeadFlag) EnumDescriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{0}
}

type HeadRPC struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RpcID int64 `protobuf:"varint,1,opt,name=rpcID,proto3" json:"rpcID,omitempty"`
}

func (x *HeadRPC) Reset() {
	*x = HeadRPC{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeadRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeadRPC) ProtoMessage() {}

func (x *HeadRPC) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeadRPC.ProtoReflect.Descriptor instead.
func (*HeadRPC) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{0}
}

func (x *HeadRPC) GetRpcID() int64 {
	if x != nil {
		return x.RpcID
	}
	return 0
}

type HeadUser struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UID int64 `protobuf:"varint,1,opt,name=UID,proto3" json:"UID,omitempty"` // 用户ID
}

func (x *HeadUser) Reset() {
	*x = HeadUser{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HeadUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeadUser) ProtoMessage() {}

func (x *HeadUser) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeadUser.ProtoReflect.Descriptor instead.
func (*HeadUser) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{1}
}

func (x *HeadUser) GetUID() int64 {
	if x != nil {
		return x.UID
	}
	return 0
}

// 消息头
type Head struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MsgID     string `protobuf:"bytes,1,opt,name=msgID,proto3" json:"msgID,omitempty"`          // 消息id，使用消息名本身来定义
	Seq       int64  `protobuf:"varint,2,opt,name=seq,proto3" json:"seq,omitempty"`             // 消息序列号，每发一个消息自增1，客户端登录成功后，服务器会分配一个开始序列号，后续会验证
	Flag      int32  `protobuf:"varint,3,opt,name=flag,proto3" json:"flag,omitempty"`           // 见 HeadFlag
	CheckSum  uint32 `protobuf:"varint,4,opt,name=checkSum,proto3" json:"checkSum,omitempty"`   // 消息体编码后的crc校检码
	ServiceID int32  `protobuf:"varint,5,opt,name=serviceID,proto3" json:"serviceID,omitempty"` // 指定发送到某台服务器，有状态的服务器使用，此服务器必须有处理该消息的逻辑
	// 以下字段根据flag来使用
	Rpc  *HeadRPC  `protobuf:"bytes,11,opt,name=rpc,proto3" json:"rpc,omitempty"`   // rpc消息相关
	User *HeadUser `protobuf:"bytes,12,opt,name=user,proto3" json:"user,omitempty"` // 用户消息相关
}

func (x *Head) Reset() {
	*x = Head{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Head) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Head) ProtoMessage() {}

func (x *Head) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Head.ProtoReflect.Descriptor instead.
func (*Head) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{2}
}

func (x *Head) GetMsgID() string {
	if x != nil {
		return x.MsgID
	}
	return ""
}

func (x *Head) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Head) GetFlag() int32 {
	if x != nil {
		return x.Flag
	}
	return 0
}

func (x *Head) GetCheckSum() uint32 {
	if x != nil {
		return x.CheckSum
	}
	return 0
}

func (x *Head) GetServiceID() int32 {
	if x != nil {
		return x.ServiceID
	}
	return 0
}

func (x *Head) GetRpc() *HeadRPC {
	if x != nil {
		return x.Rpc
	}
	return nil
}

func (x *Head) GetUser() *HeadUser {
	if x != nil {
		return x.User
	}
	return nil
}

// 消息结构
type Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Head *Head  `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"` // 消息头
	Body []byte `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"` // 消息体 经过protobuf编码 

	// 导出脚本自动加入，用于消息输出
	Ext string        // Log时额外输出的内容
	BodyMsg interface{}  // 消息结构, Msg.BodyUnMarshal和发送时填充
}

func (x *Msg) Reset() {
	*x = Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{3}
}

func (x *Msg) GetHead() *Head {
	if x != nil {
		return x.Head
	}
	return nil
}

func (x *Msg) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type TestMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Desc string `protobuf:"bytes,1,opt,name=Desc,proto3" json:"Desc,omitempty"`
}

func (x *TestMsg) Reset() {
	*x = TestMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_msg_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TestMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TestMsg) ProtoMessage() {}

func (x *TestMsg) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TestMsg.ProtoReflect.Descriptor instead.
func (*TestMsg) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{4}
}

func (x *TestMsg) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

var File_msg_proto protoreflect.FileDescriptor

var file_msg_proto_rawDesc = []byte{
	0x0a, 0x09, 0x6d, 0x73, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x6d, 0x73, 0x67,
	0x63, 0x6f, 0x64, 0x65, 0x22, 0x1f, 0x0a, 0x07, 0x48, 0x65, 0x61, 0x64, 0x52, 0x50, 0x43, 0x12,
	0x14, 0x0a, 0x05, 0x72, 0x70, 0x63, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x72, 0x70, 0x63, 0x49, 0x44, 0x22, 0x1c, 0x0a, 0x08, 0x48, 0x65, 0x61, 0x64, 0x55, 0x73, 0x65,
	0x72, 0x12, 0x10, 0x0a, 0x03, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x55, 0x49, 0x44, 0x22, 0xc7, 0x01, 0x0a, 0x04, 0x48, 0x65, 0x61, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x6d, 0x73, 0x67, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6d, 0x73, 0x67,
	0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x71, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x03, 0x73, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68, 0x65, 0x63,
	0x6b, 0x53, 0x75, 0x6d, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x63, 0x68, 0x65, 0x63,
	0x6b, 0x53, 0x75, 0x6d, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x49,
	0x44, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x49, 0x44, 0x12, 0x22, 0x0a, 0x03, 0x72, 0x70, 0x63, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x10, 0x2e, 0x6d, 0x73, 0x67, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x52, 0x50,
	0x43, 0x52, 0x03, 0x72, 0x70, 0x63, 0x12, 0x25, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x0c,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x6d, 0x73, 0x67, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x48,
	0x65, 0x61, 0x64, 0x55, 0x73, 0x65, 0x72, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x22, 0x3c, 0x0a,
	0x03, 0x4d, 0x73, 0x67, 0x12, 0x21, 0x0a, 0x04, 0x68, 0x65, 0x61, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6d, 0x73, 0x67, 0x63, 0x6f, 0x64, 0x65, 0x2e, 0x48, 0x65, 0x61,
	0x64, 0x52, 0x04, 0x68, 0x65, 0x61, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x1d, 0x0a, 0x07, 0x54,
	0x65, 0x73, 0x74, 0x4d, 0x73, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x44, 0x65, 0x73, 0x63, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x65, 0x73, 0x63, 0x2a, 0x39, 0x0a, 0x08, 0x48, 0x65,
	0x61, 0x64, 0x46, 0x6c, 0x61, 0x67, 0x12, 0x0a, 0x0a, 0x06, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x79,
	0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x50, 0x43, 0x52, 0x65, 0x71, 0x10, 0x01, 0x12, 0x0b,
	0x0a, 0x07, 0x52, 0x50, 0x43, 0x52, 0x65, 0x73, 0x70, 0x10, 0x02, 0x12, 0x08, 0x0a, 0x04, 0x55,
	0x73, 0x65, 0x72, 0x10, 0x03, 0x42, 0x0b, 0x5a, 0x09, 0x2e, 0x3b, 0x6d, 0x73, 0x67, 0x63, 0x6f,
	0x64, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_msg_proto_rawDescOnce sync.Once
	file_msg_proto_rawDescData = file_msg_proto_rawDesc
)

func file_msg_proto_rawDescGZIP() []byte {
	file_msg_proto_rawDescOnce.Do(func() {
		file_msg_proto_rawDescData = protoimpl.X.CompressGZIP(file_msg_proto_rawDescData)
	})
	return file_msg_proto_rawDescData
}

var file_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_msg_proto_goTypes = []interface{}{
	(HeadFlag)(0),    // 0: msgcode.HeadFlag
	(*HeadRPC)(nil),  // 1: msgcode.HeadRPC
	(*HeadUser)(nil), // 2: msgcode.HeadUser
	(*Head)(nil),     // 3: msgcode.Head
	(*Msg)(nil),      // 4: msgcode.Msg
	(*TestMsg)(nil),  // 5: msgcode.TestMsg
}
var file_msg_proto_depIdxs = []int32{
	1, // 0: msgcode.Head.rpc:type_name -> msgcode.HeadRPC
	2, // 1: msgcode.Head.user:type_name -> msgcode.HeadUser
	3, // 2: msgcode.Msg.head:type_name -> msgcode.Head
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_msg_proto_init() }
func file_msg_proto_init() {
	if File_msg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_msg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeadRPC); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HeadUser); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Head); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_msg_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TestMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_msg_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_proto_goTypes,
		DependencyIndexes: file_msg_proto_depIdxs,
		EnumInfos:         file_msg_proto_enumTypes,
		MessageInfos:      file_msg_proto_msgTypes,
	}.Build()
	File_msg_proto = out.File
	file_msg_proto_rawDesc = nil
	file_msg_proto_goTypes = nil
	file_msg_proto_depIdxs = nil
}
